server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: payment-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

platform:
  fee:
    rate: 0.10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always
